# Generated by Django 4.1.2 on 2022-12-13 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('auth_id', models.IntegerField(primary_key=True, serialize=False)),
                ('FSL_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.IntegerField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('house_id', models.IntegerField(primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('pages_quantity', models.IntegerField()),
                ('year_of_publishing', models.DateField()),
                ('author', models.ManyToManyField(to='booksapi.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksapi.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksapi.language')),
                ('phouse_name', models.ManyToManyField(to='booksapi.publishinghouse')),
            ],
        ),
    ]
